# Generated by Django 4.1.4 on 2023-01-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('vendor', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
