# Generated by Django 4.1.4 on 2023-01-15 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vendor',
        ),
        migrations.AddField(
            model_name='item',
            name='item_qty',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_unit_cost',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quotation_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='purchaser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_rate',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_days',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_contact',
            field=models.TextField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total',
            field=models.FloatField(default=None),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_id', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('quotation_id', models.CharField(default=None, max_length=10)),
                ('purchase_date', models.DateField(default=None)),
                ('payment_type', models.TextField(default=None)),
                ('finance_officer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
