# Generated by Django 4.1.4 on 2023-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_quotation_date_remove_quotation_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
