# Generated by Django 4.1.4 on 2023-01-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quotation_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_contact',
            field=models.TextField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_email',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_email',
            field=models.TextField(default=None),
        ),
    ]
