# Generated by Django 4.1.4 on 2023-01-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quotation_client_contact_quotation_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_description',
        ),
        migrations.AddField(
            model_name='item',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
