# Generated by Django 4.1.4 on 2023-01-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_item_item_description_item_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purchased',
            new_name='item_purchased',
        ),
    ]
