# Generated by Django 4.1.4 on 2023-01-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_purchased_item_item_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_total_cost',
            field=models.FloatField(default=None, null=True),
        ),
    ]
