# Generated by Django 4.1.4 on 2023-01-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_item_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_subtotal',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_total',
            field=models.FloatField(default=None),
        ),
    ]
