# Generated by Django 4.1.4 on 2023-01-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchaseorder_purchase_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quotation_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.quotation'),
        ),
    ]
