# Generated by Django 4.1.4 on 2023-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_purchaseorder_quotation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_address',
            field=models.TextField(default=None),
        ),
    ]
