# Generated by Django 4.1.4 on 2023-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_purchaseorder_purchase_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
