# Generated by Django 4.1.4 on 2023-01-26 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quotation_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRTable',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_Stats', models.CharField(blank=True, max_length=10, null=True)),
                ('form_Date', models.DateField(default=datetime.date.today)),
                ('delv_Date', models.DateField(default=datetime.date.today)),
                ('delv_Address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='QTable',
            fields=[
                ('quotation_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('purchaser_Name', models.CharField(max_length=30)),
                ('delv_Address', models.CharField(max_length=70)),
                ('vendor_Name', models.CharField(max_length=50)),
                ('vendor_Address', models.CharField(max_length=70)),
                ('quotation_Stats', models.CharField(max_length=10)),
                ('quotation_Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='QITable',
            fields=[
                ('item_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_Description', models.TextField(max_length=30)),
                ('item_Quantity', models.IntegerField()),
                ('item_unitPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_totalPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quotation_ID', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.qtable')),
            ],
        ),
        migrations.CreateModel(
            name='PRITable',
            fields=[
                ('item_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_Description', models.TextField(max_length=30)),
                ('item_Quantity', models.IntegerField()),
                ('item_unitPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item_totalPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prtable')),
            ],
        ),
    ]
