# Generated by Django 4.1.4 on 2023-01-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_prtable_qtable_qitable_pritable'),
    ]

    operations = [
        migrations.AddField(
            model_name='prtable',
            name='emp_Name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='prtable',
            name='emp_id',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
