# Generated by Django 4.1.4 on 2023-01-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_prtable_emp_name_prtable_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pritable',
            old_name='item_ID',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='prtable',
            name='form_Stats',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
