# Generated by Django 4.1.4 on 2023-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_item_id_pritable_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritable',
            name='item_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prtable',
            name='pr_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
