# Generated by Django 4.1.4 on 2023-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_pritable_item_id_alter_prtable_pr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pritable',
            name='item_totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pritable',
            name='item_unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
