# Generated by Django 4.1.5 on 2023-01-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_pritable_item_totalprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qitable',
            old_name='item_ID',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='qitable',
            old_name='quotation_ID',
            new_name='quotation_id',
        ),
        migrations.AddField(
            model_name='qtable',
            name='purchaser_id',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='qitable',
            name='item_totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='qitable',
            name='item_unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='qtable',
            name='quotation_Stats',
            field=models.TextField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
