# Generated by Django 4.1.5 on 2023-01-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_item_id_qitable_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qitable',
            name='quotation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qtable'),
        ),
    ]
