# Generated by Django 4.1.5 on 2023-01-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_qitable_quotation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qitable',
            old_name='quotation_id',
            new_name='quotation_ID',
        ),
    ]
