# Generated by Django 4.1.5 on 2023-01-27 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_quotation_id_qitable_quotation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='POTable',
            fields=[
                ('po_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fo_id', models.CharField(default=None, max_length=6)),
                ('fo_Name', models.CharField(max_length=30)),
                ('delv_Address', models.CharField(max_length=70)),
                ('vendor_Name', models.CharField(max_length=50)),
                ('vendor_Address', models.CharField(max_length=70)),
                ('quotation_Stats', models.TextField(choices=[('Generated', 'Generated'), ('Pending', 'Pending')], default='Pending')),
                ('po_Date', models.DateField(default=datetime.date.today)),
                ('quotation_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.qtable')),
            ],
        ),
    ]
