# Generated by Django 4.1.5 on 2023-01-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_potable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potable',
            old_name='quotation_Stats',
            new_name='po_Stats',
        ),
    ]
