# Generated by Django 4.1.4 on 2023-01-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_quotation_stats_potable_po_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potable',
            name='po_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
