# Generated by Django 4.1.5 on 2023-01-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_potable_po_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='POITable',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_Description', models.TextField(max_length=30)),
                ('item_Quantity', models.IntegerField()),
                ('item_unitPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('item_totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.potable')),
            ],
        ),
    ]
