# Generated by Django 4.1.4 on 2023-01-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_potable_po_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='finance_officer',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='purchaser',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
